### ISSUE TITLE
示例

### ISSUE THREAD

**Issue by zhuzimei** [Spico197/Mirror#4]
您好
请问您这里有中文的Multi-span Extraction (e.g. Discontinuous NER)示例与中文NER的示例吗
其中可以实现不连续的实体嵌套效果吗
例如：“国内外知名专家”中 提取出地区类别的“国内”与“国外”
其中与训练与微调示例可以正常实现但是在似乎没有看到关于不连续实体识别的相关数据集与示例
您这边是否可以提供呢

**Comment by Spico197** [comment]
感谢您对本工作的关注~

抱歉，我们没有收集中文的非连续实体数据集，如果您有数据集的话，可以使用中文语料训练Mirror。旧版Mirror是在中文语料上进行的，不过只支持flat NER，现在有一些兼容性问题待查 #2

**Comment by zhuzimei** [comment]
那是否有英文的非连续实体识别的示例和相关的数据集呢
您这边方便提供一下吗

**Comment by Spico197** [comment]
好嘞。这里是我们论文里用到的CADEC数据：https://huggingface.co/datasets/Spico/Mirror/tree/main/CADEC
