### ISSUE TITLE
ACE04, ACE05数据集处理

### ISSUE THREAD

**Issue by baokemi** [Spico197/Mirror#7]
您好，我发现经过uie代码处理后的ACE04, ACE05与您提供的其他数据集格式存在明显的差异，请问我应该如何处理ACE04, ACE05数据集才能在您的项目中运行

**Comment by Spico197** [comment]
嗨您好，我们是从OneIE的数据版本转成Mirror格式的，因为那一版数据有明确的位置。
我找找看还有没有相关的转换脚本。如果没找到的话，麻烦您邮件给我发下你们的数据，我确认之后直接把已经转换好的数据发给你们，避免版权问题orz

**Comment by Spico197** [comment]
嗨，数据处理放在这里啦：https://gist.github.com/Spico197/94c4ae68292e9ac6073c0d8854c0fb4a

Instruction部分是后面再加的，可以参考其它同类型任务数据中的intruction，进行随机采样替换。如果想直接获取我们的数据，方便复现论文结果的话，可以邮件发20条ace04/05的原始数据sample给我，确认你们有license之后我会把数据发给你们。

感谢您对我们工作的支持！

**Comment by baokemi** [comment]
您好，我已将原始数据集发送到了您的论文邮箱地址，非常感谢您的回复🙇‍。

发件人："Tong Zhu (朱桐)" ***@***.***>
发送日期：2024-05-09 15:36:31
收件人：Spico197/Mirror ***@***.***>
抄送人：baokemi ***@***.***>,Author ***@***.***>
主题：Re: [Spico197/Mirror] ACE04, ACE05数据集处理 (Issue #7)

嗨，数据处理放在这里啦：https://gist.github.com/Spico197/94c4ae68292e9ac6073c0d8854c0fb4a
Instruction部分是后面再加的，可以参考其它同类型任务数据中的intruction，进行随机采样替换。如果想直接获取我们的数据，方便复现论文结果的话，可以邮件发20条ace04/05的原始数据sample给我，确认你们有license之后我会把数据发给你们。
感谢您对我们工作的支持！

**Comment by Spico197** [comment]
嗨您好，已经回复您的邮件啦，请注意查收，祝实验顺利！

**Comment by baokemi** [comment]
非常感谢您快速的回复，祝您科研顺利！
